name: goodboy
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^5.0.1
  equatable: ^1.2.2
  provider: ^4.3.1
  googleapis_auth: ^0.2.12
  dio: ^3.0.9
  image_picker: ^0.6.7+4
  carousel_slider: ^2.2.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/bot.png"
  image_path_android: "assets/bot.png"

flutter:

  uses-material-design: true

  assets:
    - keys/goodboy-daoseh-7071342db28c.json
    - assets/bot.png